name: Dependabot
on: [pull_request]

jobs:
  dependabot:
    name: Dependabot
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' &&
      (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
    steps:
      - name: Add "@dependabot merge" comment
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GH_ACCESS_TOKEN}}
          script: |
            github.issues.createComment({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              body: '@dependabot merge'
            })